apiVersion: v1
kind: PersistentVolume
metadata:
  name: cert-pv
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: "/data/cert"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cert-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi

